services:
  streamlit:
    build: .
    ports:
      - "3000:8501"  # Changed external port to 3000
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_SERVER_ADDRESS="v0sw4s8c4kcwwwks4w448ok8.104.37.187.180.sslip.io"
    networks:
      - coolify
    restart: always

networks:
  coolify:
    external: true
